#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BancoDados")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void InsertHospitai(Hospitai instance);
    partial void UpdateHospitai(Hospitai instance);
    partial void DeleteHospitai(Hospitai instance);
    partial void InsertMedico(Medico instance);
    partial void UpdateMedico(Medico instance);
    partial void DeleteMedico(Medico instance);
    partial void InsertMedicoHospital(MedicoHospital instance);
    partial void UpdateMedicoHospital(MedicoHospital instance);
    partial void DeleteMedicoHospital(MedicoHospital instance);
    partial void InsertConvenio(Convenio instance);
    partial void UpdateConvenio(Convenio instance);
    partial void DeleteConvenio(Convenio instance);
    partial void InsertConvenioHosptal(ConvenioHosptal instance);
    partial void UpdateConvenioHosptal(ConvenioHosptal instance);
    partial void DeleteConvenioHosptal(ConvenioHosptal instance);
    partial void InsertPaciente(Paciente instance);
    partial void UpdatePaciente(Paciente instance);
    partial void DeletePaciente(Paciente instance);
    partial void InsertHospitalConvenio(HospitalConvenio instance);
    partial void UpdateHospitalConvenio(HospitalConvenio instance);
    partial void DeleteHospitalConvenio(HospitalConvenio instance);
    partial void InsertFornecedore(Fornecedore instance);
    partial void UpdateFornecedore(Fornecedore instance);
    partial void DeleteFornecedore(Fornecedore instance);
    partial void InsertCirurgia(Cirurgia instance);
    partial void UpdateCirurgia(Cirurgia instance);
    partial void DeleteCirurgia(Cirurgia instance);
    partial void InsertCirurgiaFornecedor(CirurgiaFornecedor instance);
    partial void UpdateCirurgiaFornecedor(CirurgiaFornecedor instance);
    partial void DeleteCirurgiaFornecedor(CirurgiaFornecedor instance);
    partial void InsertStatusCirurgia(StatusCirurgia instance);
    partial void UpdateStatusCirurgia(StatusCirurgia instance);
    partial void DeleteStatusCirurgia(StatusCirurgia instance);
    partial void InsertConsultasMedica(ConsultasMedica instance);
    partial void UpdateConsultasMedica(ConsultasMedica instance);
    partial void DeleteConsultasMedica(ConsultasMedica instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::WindowsFormsApp.Properties.Settings.Default.BancoDadosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<Hospitai> Hospitais
		{
			get
			{
				return this.GetTable<Hospitai>();
			}
		}
		
		public System.Data.Linq.Table<Medico> Medicos
		{
			get
			{
				return this.GetTable<Medico>();
			}
		}
		
		public System.Data.Linq.Table<MedicoHospital> MedicoHospitals
		{
			get
			{
				return this.GetTable<MedicoHospital>();
			}
		}
		
		public System.Data.Linq.Table<Convenio> Convenios
		{
			get
			{
				return this.GetTable<Convenio>();
			}
		}
		
		public System.Data.Linq.Table<ConvenioHosptal> ConvenioHosptals
		{
			get
			{
				return this.GetTable<ConvenioHosptal>();
			}
		}
		
		public System.Data.Linq.Table<Paciente> Pacientes
		{
			get
			{
				return this.GetTable<Paciente>();
			}
		}
		
		public System.Data.Linq.Table<HospitalConvenio> HospitalConvenios
		{
			get
			{
				return this.GetTable<HospitalConvenio>();
			}
		}
		
		public System.Data.Linq.Table<Fornecedore> Fornecedores
		{
			get
			{
				return this.GetTable<Fornecedore>();
			}
		}
		
		public System.Data.Linq.Table<Cirurgia> Cirurgias
		{
			get
			{
				return this.GetTable<Cirurgia>();
			}
		}
		
		public System.Data.Linq.Table<CirurgiaFornecedor> CirurgiaFornecedors
		{
			get
			{
				return this.GetTable<CirurgiaFornecedor>();
			}
		}
		
		public System.Data.Linq.Table<StatusCirurgia> StatusCirurgias
		{
			get
			{
				return this.GetTable<StatusCirurgia>();
			}
		}
		
		public System.Data.Linq.Table<ConsultasMedica> ConsultasMedicas
		{
			get
			{
				return this.GetTable<ConsultasMedica>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _userName;
		
		private string _password;
		
		private int _access;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnaccessChanging(int value);
    partial void OnaccessChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access", DbType="Int NOT NULL")]
		public int access
		{
			get
			{
				return this._access;
			}
			set
			{
				if ((this._access != value))
				{
					this.OnaccessChanging(value);
					this.SendPropertyChanging();
					this._access = value;
					this.SendPropertyChanged("access");
					this.OnaccessChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hospitais")]
	public partial class Hospitai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nome;
		
		private string _CNPJ;
		
		private string _Unidade;
		
		private string _Endereco;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _CEP;
		
		private string _Contato1;
		
		private string _Email1;
		
		private string _Telefone1;
		
		private string _Contato2;
		
		private string _Email2;
		
		private string _Telefone2;
		
		private string _Contato3;
		
		private string _Email3;
		
		private string _Telefone3;
		
		private string _Contato4;
		
		private string _Email4;
		
		private string _Telefone4;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCNPJChanging(string value);
    partial void OnCNPJChanged();
    partial void OnUnidadeChanging(string value);
    partial void OnUnidadeChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnContato1Changing(string value);
    partial void OnContato1Changed();
    partial void OnEmail1Changing(string value);
    partial void OnEmail1Changed();
    partial void OnTelefone1Changing(string value);
    partial void OnTelefone1Changed();
    partial void OnContato2Changing(string value);
    partial void OnContato2Changed();
    partial void OnEmail2Changing(string value);
    partial void OnEmail2Changed();
    partial void OnTelefone2Changing(string value);
    partial void OnTelefone2Changed();
    partial void OnContato3Changing(string value);
    partial void OnContato3Changed();
    partial void OnEmail3Changing(string value);
    partial void OnEmail3Changed();
    partial void OnTelefone3Changing(string value);
    partial void OnTelefone3Changed();
    partial void OnContato4Changing(string value);
    partial void OnContato4Changed();
    partial void OnEmail4Changing(string value);
    partial void OnEmail4Changed();
    partial void OnTelefone4Changing(string value);
    partial void OnTelefone4Changed();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public Hospitai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CNPJ
		{
			get
			{
				return this._CNPJ;
			}
			set
			{
				if ((this._CNPJ != value))
				{
					this.OnCNPJChanging(value);
					this.SendPropertyChanging();
					this._CNPJ = value;
					this.SendPropertyChanged("CNPJ");
					this.OnCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unidade", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Unidade
		{
			get
			{
				return this._Unidade;
			}
			set
			{
				if ((this._Unidade != value))
				{
					this.OnUnidadeChanging(value);
					this.SendPropertyChanging();
					this._Unidade = value;
					this.SendPropertyChanged("Unidade");
					this.OnUnidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(50)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(10)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contato1", DbType="VarChar(30)")]
		public string Contato1
		{
			get
			{
				return this._Contato1;
			}
			set
			{
				if ((this._Contato1 != value))
				{
					this.OnContato1Changing(value);
					this.SendPropertyChanging();
					this._Contato1 = value;
					this.SendPropertyChanged("Contato1");
					this.OnContato1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email1", DbType="VarChar(30)")]
		public string Email1
		{
			get
			{
				return this._Email1;
			}
			set
			{
				if ((this._Email1 != value))
				{
					this.OnEmail1Changing(value);
					this.SendPropertyChanging();
					this._Email1 = value;
					this.SendPropertyChanged("Email1");
					this.OnEmail1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone1", DbType="VarChar(30)")]
		public string Telefone1
		{
			get
			{
				return this._Telefone1;
			}
			set
			{
				if ((this._Telefone1 != value))
				{
					this.OnTelefone1Changing(value);
					this.SendPropertyChanging();
					this._Telefone1 = value;
					this.SendPropertyChanged("Telefone1");
					this.OnTelefone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contato2", DbType="VarChar(30)")]
		public string Contato2
		{
			get
			{
				return this._Contato2;
			}
			set
			{
				if ((this._Contato2 != value))
				{
					this.OnContato2Changing(value);
					this.SendPropertyChanging();
					this._Contato2 = value;
					this.SendPropertyChanged("Contato2");
					this.OnContato2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email2", DbType="VarChar(30)")]
		public string Email2
		{
			get
			{
				return this._Email2;
			}
			set
			{
				if ((this._Email2 != value))
				{
					this.OnEmail2Changing(value);
					this.SendPropertyChanging();
					this._Email2 = value;
					this.SendPropertyChanged("Email2");
					this.OnEmail2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone2", DbType="VarChar(30)")]
		public string Telefone2
		{
			get
			{
				return this._Telefone2;
			}
			set
			{
				if ((this._Telefone2 != value))
				{
					this.OnTelefone2Changing(value);
					this.SendPropertyChanging();
					this._Telefone2 = value;
					this.SendPropertyChanged("Telefone2");
					this.OnTelefone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contato3", DbType="VarChar(30)")]
		public string Contato3
		{
			get
			{
				return this._Contato3;
			}
			set
			{
				if ((this._Contato3 != value))
				{
					this.OnContato3Changing(value);
					this.SendPropertyChanging();
					this._Contato3 = value;
					this.SendPropertyChanged("Contato3");
					this.OnContato3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email3", DbType="VarChar(30)")]
		public string Email3
		{
			get
			{
				return this._Email3;
			}
			set
			{
				if ((this._Email3 != value))
				{
					this.OnEmail3Changing(value);
					this.SendPropertyChanging();
					this._Email3 = value;
					this.SendPropertyChanged("Email3");
					this.OnEmail3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone3", DbType="VarChar(30)")]
		public string Telefone3
		{
			get
			{
				return this._Telefone3;
			}
			set
			{
				if ((this._Telefone3 != value))
				{
					this.OnTelefone3Changing(value);
					this.SendPropertyChanging();
					this._Telefone3 = value;
					this.SendPropertyChanged("Telefone3");
					this.OnTelefone3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contato4", DbType="VarChar(30)")]
		public string Contato4
		{
			get
			{
				return this._Contato4;
			}
			set
			{
				if ((this._Contato4 != value))
				{
					this.OnContato4Changing(value);
					this.SendPropertyChanging();
					this._Contato4 = value;
					this.SendPropertyChanged("Contato4");
					this.OnContato4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email4", DbType="VarChar(30)")]
		public string Email4
		{
			get
			{
				return this._Email4;
			}
			set
			{
				if ((this._Email4 != value))
				{
					this.OnEmail4Changing(value);
					this.SendPropertyChanging();
					this._Email4 = value;
					this.SendPropertyChanged("Email4");
					this.OnEmail4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone4", DbType="VarChar(30)")]
		public string Telefone4
		{
			get
			{
				return this._Telefone4;
			}
			set
			{
				if ((this._Telefone4 != value))
				{
					this.OnTelefone4Changing(value);
					this.SendPropertyChanging();
					this._Telefone4 = value;
					this.SendPropertyChanged("Telefone4");
					this.OnTelefone4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Medicos")]
	public partial class Medico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _CRO_CRM;
		
		private string _Nome;
		
		private string _Especialidade;
		
		private string _Endereco;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _CEP;
		
		private string _Telefone1;
		
		private string _Telefone2;
		
		private string _Consultorio;
		
		private string _Celular;
		
		private string _Email;
		
		private string _Secretaria;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCRO_CRMChanging(string value);
    partial void OnCRO_CRMChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEspecialidadeChanging(string value);
    partial void OnEspecialidadeChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnTelefone1Changing(string value);
    partial void OnTelefone1Changed();
    partial void OnTelefone2Changing(string value);
    partial void OnTelefone2Changed();
    partial void OnConsultorioChanging(string value);
    partial void OnConsultorioChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSecretariaChanging(string value);
    partial void OnSecretariaChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public Medico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRO_CRM", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CRO_CRM
		{
			get
			{
				return this._CRO_CRM;
			}
			set
			{
				if ((this._CRO_CRM != value))
				{
					this.OnCRO_CRMChanging(value);
					this.SendPropertyChanging();
					this._CRO_CRM = value;
					this.SendPropertyChanged("CRO_CRM");
					this.OnCRO_CRMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidade", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Especialidade
		{
			get
			{
				return this._Especialidade;
			}
			set
			{
				if ((this._Especialidade != value))
				{
					this.OnEspecialidadeChanging(value);
					this.SendPropertyChanging();
					this._Especialidade = value;
					this.SendPropertyChanged("Especialidade");
					this.OnEspecialidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(50)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(30)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(5)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(10)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone1", DbType="VarChar(20)")]
		public string Telefone1
		{
			get
			{
				return this._Telefone1;
			}
			set
			{
				if ((this._Telefone1 != value))
				{
					this.OnTelefone1Changing(value);
					this.SendPropertyChanging();
					this._Telefone1 = value;
					this.SendPropertyChanged("Telefone1");
					this.OnTelefone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone2", DbType="VarChar(20)")]
		public string Telefone2
		{
			get
			{
				return this._Telefone2;
			}
			set
			{
				if ((this._Telefone2 != value))
				{
					this.OnTelefone2Changing(value);
					this.SendPropertyChanging();
					this._Telefone2 = value;
					this.SendPropertyChanged("Telefone2");
					this.OnTelefone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Consultorio", DbType="VarChar(50)")]
		public string Consultorio
		{
			get
			{
				return this._Consultorio;
			}
			set
			{
				if ((this._Consultorio != value))
				{
					this.OnConsultorioChanging(value);
					this.SendPropertyChanging();
					this._Consultorio = value;
					this.SendPropertyChanged("Consultorio");
					this.OnConsultorioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(20)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secretaria", DbType="VarChar(30)")]
		public string Secretaria
		{
			get
			{
				return this._Secretaria;
			}
			set
			{
				if ((this._Secretaria != value))
				{
					this.OnSecretariaChanging(value);
					this.SendPropertyChanging();
					this._Secretaria = value;
					this.SendPropertyChanged("Secretaria");
					this.OnSecretariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MedicoHospital")]
	public partial class MedicoHospital : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _MedicoId;
		
		private int _HospitalId;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMedicoIdChanging(int value);
    partial void OnMedicoIdChanged();
    partial void OnHospitalIdChanging(int value);
    partial void OnHospitalIdChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public MedicoHospital()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicoId", DbType="Int NOT NULL")]
		public int MedicoId
		{
			get
			{
				return this._MedicoId;
			}
			set
			{
				if ((this._MedicoId != value))
				{
					this.OnMedicoIdChanging(value);
					this.SendPropertyChanging();
					this._MedicoId = value;
					this.SendPropertyChanged("MedicoId");
					this.OnMedicoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospitalId", DbType="Int NOT NULL")]
		public int HospitalId
		{
			get
			{
				return this._HospitalId;
			}
			set
			{
				if ((this._HospitalId != value))
				{
					this.OnHospitalIdChanging(value);
					this.SendPropertyChanging();
					this._HospitalId = value;
					this.SendPropertyChanged("HospitalId");
					this.OnHospitalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Convenios")]
	public partial class Convenio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nome;
		
		private string _Plano;
		
		private string _Acomodacao;
		
		private string _Endereco;
		
		private string _Contato;
		
		private string _Telefone;
		
		private string _UF;
		
		private string _CEP;
		
		private string _Cidade;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnPlanoChanging(string value);
    partial void OnPlanoChanged();
    partial void OnAcomodacaoChanging(string value);
    partial void OnAcomodacaoChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnContatoChanging(string value);
    partial void OnContatoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Convenio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plano", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Plano
		{
			get
			{
				return this._Plano;
			}
			set
			{
				if ((this._Plano != value))
				{
					this.OnPlanoChanging(value);
					this.SendPropertyChanging();
					this._Plano = value;
					this.SendPropertyChanged("Plano");
					this.OnPlanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acomodacao", DbType="VarChar(30)")]
		public string Acomodacao
		{
			get
			{
				return this._Acomodacao;
			}
			set
			{
				if ((this._Acomodacao != value))
				{
					this.OnAcomodacaoChanging(value);
					this.SendPropertyChanging();
					this._Acomodacao = value;
					this.SendPropertyChanged("Acomodacao");
					this.OnAcomodacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(50)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contato", DbType="VarChar(30)")]
		public string Contato
		{
			get
			{
				return this._Contato;
			}
			set
			{
				if ((this._Contato != value))
				{
					this.OnContatoChanging(value);
					this.SendPropertyChanging();
					this._Contato = value;
					this.SendPropertyChanged("Contato");
					this.OnContatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(30)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(10)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(30)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConvenioHosptal")]
	public partial class ConvenioHosptal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _ConvenioId;
		
		private int _HospitalId;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnConvenioIdChanging(int value);
    partial void OnConvenioIdChanged();
    partial void OnHospitalIdChanging(int value);
    partial void OnHospitalIdChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public ConvenioHosptal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConvenioId", DbType="Int NOT NULL")]
		public int ConvenioId
		{
			get
			{
				return this._ConvenioId;
			}
			set
			{
				if ((this._ConvenioId != value))
				{
					this.OnConvenioIdChanging(value);
					this.SendPropertyChanging();
					this._ConvenioId = value;
					this.SendPropertyChanged("ConvenioId");
					this.OnConvenioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospitalId", DbType="Int NOT NULL")]
		public int HospitalId
		{
			get
			{
				return this._HospitalId;
			}
			set
			{
				if ((this._HospitalId != value))
				{
					this.OnHospitalIdChanging(value);
					this.SendPropertyChanging();
					this._HospitalId = value;
					this.SendPropertyChanged("HospitalId");
					this.OnHospitalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pacientes")]
	public partial class Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _CPF;
		
		private string _Nome;
		
		private System.Nullable<System.DateTime> _DataNasc;
		
		private string _Endereco;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _Telefone;
		
		private string _Celular;
		
		private string _Email;
		
		private int _ConvenioId;
		
		private string _NoCarteirinha;
		
		private System.Nullable<System.DateTime> _Validade;
		
		private string _Login;
		
		private string _Senha;
		
		private int _MedicoId;
		
		private System.DateTime _createdAt;
		
		private System.DateTime _updatedAt;
		
		private string _obs;
		
		private System.Nullable<System.DateTime> _Inclusao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDataNascChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNascChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnConvenioIdChanging(int value);
    partial void OnConvenioIdChanged();
    partial void OnNoCarteirinhaChanging(string value);
    partial void OnNoCarteirinhaChanged();
    partial void OnValidadeChanging(System.Nullable<System.DateTime> value);
    partial void OnValidadeChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnMedicoIdChanging(int value);
    partial void OnMedicoIdChanged();
    partial void OncreatedAtChanging(System.DateTime value);
    partial void OncreatedAtChanged();
    partial void OnupdatedAtChanging(System.DateTime value);
    partial void OnupdatedAtChanged();
    partial void OnobsChanging(string value);
    partial void OnobsChanged();
    partial void OnInclusaoChanging(System.Nullable<System.DateTime> value);
    partial void OnInclusaoChanged();
    #endregion
		
		public Paciente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNasc", DbType="Date")]
		public System.Nullable<System.DateTime> DataNasc
		{
			get
			{
				return this._DataNasc;
			}
			set
			{
				if ((this._DataNasc != value))
				{
					this.OnDataNascChanging(value);
					this.SendPropertyChanging();
					this._DataNasc = value;
					this.SendPropertyChanged("DataNasc");
					this.OnDataNascChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(50)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(30)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(30)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(30)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(30)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConvenioId", DbType="Int NOT NULL")]
		public int ConvenioId
		{
			get
			{
				return this._ConvenioId;
			}
			set
			{
				if ((this._ConvenioId != value))
				{
					this.OnConvenioIdChanging(value);
					this.SendPropertyChanging();
					this._ConvenioId = value;
					this.SendPropertyChanged("ConvenioId");
					this.OnConvenioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCarteirinha", DbType="VarChar(50)")]
		public string NoCarteirinha
		{
			get
			{
				return this._NoCarteirinha;
			}
			set
			{
				if ((this._NoCarteirinha != value))
				{
					this.OnNoCarteirinhaChanging(value);
					this.SendPropertyChanging();
					this._NoCarteirinha = value;
					this.SendPropertyChanged("NoCarteirinha");
					this.OnNoCarteirinhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validade", DbType="Date")]
		public System.Nullable<System.DateTime> Validade
		{
			get
			{
				return this._Validade;
			}
			set
			{
				if ((this._Validade != value))
				{
					this.OnValidadeChanging(value);
					this.SendPropertyChanging();
					this._Validade = value;
					this.SendPropertyChanged("Validade");
					this.OnValidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(50)")]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(50)")]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicoId", DbType="Int NOT NULL")]
		public int MedicoId
		{
			get
			{
				return this._MedicoId;
			}
			set
			{
				if ((this._MedicoId != value))
				{
					this.OnMedicoIdChanging(value);
					this.SendPropertyChanging();
					this._MedicoId = value;
					this.SendPropertyChanged("MedicoId");
					this.OnMedicoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this.OnupdatedAtChanging(value);
					this.SendPropertyChanging();
					this._updatedAt = value;
					this.SendPropertyChanged("updatedAt");
					this.OnupdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs", DbType="VarChar(255)")]
		public string obs
		{
			get
			{
				return this._obs;
			}
			set
			{
				if ((this._obs != value))
				{
					this.OnobsChanging(value);
					this.SendPropertyChanging();
					this._obs = value;
					this.SendPropertyChanged("obs");
					this.OnobsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inclusao", DbType="Date")]
		public System.Nullable<System.DateTime> Inclusao
		{
			get
			{
				return this._Inclusao;
			}
			set
			{
				if ((this._Inclusao != value))
				{
					this.OnInclusaoChanging(value);
					this.SendPropertyChanging();
					this._Inclusao = value;
					this.SendPropertyChanged("Inclusao");
					this.OnInclusaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HospitalConvenio")]
	public partial class HospitalConvenio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _HospitalId;
		
		private int _ConvenioId;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnHospitalIdChanging(int value);
    partial void OnHospitalIdChanged();
    partial void OnConvenioIdChanging(int value);
    partial void OnConvenioIdChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public HospitalConvenio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospitalId", DbType="Int NOT NULL")]
		public int HospitalId
		{
			get
			{
				return this._HospitalId;
			}
			set
			{
				if ((this._HospitalId != value))
				{
					this.OnHospitalIdChanging(value);
					this.SendPropertyChanging();
					this._HospitalId = value;
					this.SendPropertyChanged("HospitalId");
					this.OnHospitalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConvenioId", DbType="Int NOT NULL")]
		public int ConvenioId
		{
			get
			{
				return this._ConvenioId;
			}
			set
			{
				if ((this._ConvenioId != value))
				{
					this.OnConvenioIdChanging(value);
					this.SendPropertyChanging();
					this._ConvenioId = value;
					this.SendPropertyChanged("ConvenioId");
					this.OnConvenioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fornecedores")]
	public partial class Fornecedore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _CNPJ;
		
		private string _Nome;
		
		private string _Endereco;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _CEP;
		
		private string _Contato;
		
		private string _Telefone;
		
		private string _Email;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCNPJChanging(string value);
    partial void OnCNPJChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnContatoChanging(string value);
    partial void OnContatoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public Fornecedore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CNPJ
		{
			get
			{
				return this._CNPJ;
			}
			set
			{
				if ((this._CNPJ != value))
				{
					this.OnCNPJChanging(value);
					this.SendPropertyChanging();
					this._CNPJ = value;
					this.SendPropertyChanged("CNPJ");
					this.OnCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(50)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(15)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contato", DbType="VarChar(50)")]
		public string Contato
		{
			get
			{
				return this._Contato;
			}
			set
			{
				if ((this._Contato != value))
				{
					this.OnContatoChanging(value);
					this.SendPropertyChanging();
					this._Contato = value;
					this.SendPropertyChanged("Contato");
					this.OnContatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(30)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cirurgias")]
	public partial class Cirurgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nome;
		
		private string _CID;
		
		private string _TUS;
		
		private string _Materiais;
		
		private string _Justificativa;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCIDChanging(string value);
    partial void OnCIDChanged();
    partial void OnTUSChanging(string value);
    partial void OnTUSChanged();
    partial void OnMateriaisChanging(string value);
    partial void OnMateriaisChanged();
    partial void OnJustificativaChanging(string value);
    partial void OnJustificativaChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public Cirurgia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CID
		{
			get
			{
				return this._CID;
			}
			set
			{
				if ((this._CID != value))
				{
					this.OnCIDChanging(value);
					this.SendPropertyChanging();
					this._CID = value;
					this.SendPropertyChanged("CID");
					this.OnCIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUS", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TUS
		{
			get
			{
				return this._TUS;
			}
			set
			{
				if ((this._TUS != value))
				{
					this.OnTUSChanging(value);
					this.SendPropertyChanging();
					this._TUS = value;
					this.SendPropertyChanged("TUS");
					this.OnTUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materiais", DbType="VarChar(50)")]
		public string Materiais
		{
			get
			{
				return this._Materiais;
			}
			set
			{
				if ((this._Materiais != value))
				{
					this.OnMateriaisChanging(value);
					this.SendPropertyChanging();
					this._Materiais = value;
					this.SendPropertyChanged("Materiais");
					this.OnMateriaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Justificativa", DbType="VarChar(50)")]
		public string Justificativa
		{
			get
			{
				return this._Justificativa;
			}
			set
			{
				if ((this._Justificativa != value))
				{
					this.OnJustificativaChanging(value);
					this.SendPropertyChanging();
					this._Justificativa = value;
					this.SendPropertyChanged("Justificativa");
					this.OnJustificativaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CirurgiaFornecedor")]
	public partial class CirurgiaFornecedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _CirurgiaId;
		
		private int _FornecedorId;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCirurgiaIdChanging(int value);
    partial void OnCirurgiaIdChanged();
    partial void OnFornecedorIdChanging(int value);
    partial void OnFornecedorIdChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public CirurgiaFornecedor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CirurgiaId", DbType="Int NOT NULL")]
		public int CirurgiaId
		{
			get
			{
				return this._CirurgiaId;
			}
			set
			{
				if ((this._CirurgiaId != value))
				{
					this.OnCirurgiaIdChanging(value);
					this.SendPropertyChanging();
					this._CirurgiaId = value;
					this.SendPropertyChanged("CirurgiaId");
					this.OnCirurgiaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FornecedorId", DbType="Int NOT NULL")]
		public int FornecedorId
		{
			get
			{
				return this._FornecedorId;
			}
			set
			{
				if ((this._FornecedorId != value))
				{
					this.OnFornecedorIdChanging(value);
					this.SendPropertyChanging();
					this._FornecedorId = value;
					this.SendPropertyChanged("FornecedorId");
					this.OnFornecedorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatusCirurgias")]
	public partial class StatusCirurgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _options;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnoptionsChanging(string value);
    partial void OnoptionsChanged();
    #endregion
		
		public StatusCirurgia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_options", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string options
		{
			get
			{
				return this._options;
			}
			set
			{
				if ((this._options != value))
				{
					this.OnoptionsChanging(value);
					this.SendPropertyChanging();
					this._options = value;
					this.SendPropertyChanged("options");
					this.OnoptionsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConsultasMedicas")]
	public partial class ConsultasMedica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _PacienteId;
		
		private int _MedicoId;
		
		private int _HospitalId;
		
		private int _CirurgiaId;
		
		private int _FornecedorId;
		
		private string _Historico;
		
		private System.Nullable<System.DateTime> _DataConsulta;
		
		private string _Queixa;
		
		private string _HistoriaDoenca;
		
		private string _ExameFisico;
		
		private string _Diagnostico;
		
		private string _Exames;
		
		private System.Nullable<bool> _IndicacaoCirurgia;
		
		private System.Nullable<System.DateTime> _DataPrevista;
		
		private string _ResultadoEsperado;
		
		private string _Justificativa;
		
		private string _PlanejamentoCirurgico;
		
		private System.DateTime _CreatedAt;
		
		private System.DateTime _UpdatedAt;
		
		private System.Nullable<System.DateTime> _DataCirurgia;
		
		private System.Nullable<int> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPacienteIdChanging(int value);
    partial void OnPacienteIdChanged();
    partial void OnMedicoIdChanging(int value);
    partial void OnMedicoIdChanged();
    partial void OnHospitalIdChanging(int value);
    partial void OnHospitalIdChanged();
    partial void OnCirurgiaIdChanging(int value);
    partial void OnCirurgiaIdChanged();
    partial void OnFornecedorIdChanging(int value);
    partial void OnFornecedorIdChanged();
    partial void OnHistoricoChanging(string value);
    partial void OnHistoricoChanged();
    partial void OnDataConsultaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataConsultaChanged();
    partial void OnQueixaChanging(string value);
    partial void OnQueixaChanged();
    partial void OnHistoriaDoencaChanging(string value);
    partial void OnHistoriaDoencaChanged();
    partial void OnExameFisicoChanging(string value);
    partial void OnExameFisicoChanged();
    partial void OnDiagnosticoChanging(string value);
    partial void OnDiagnosticoChanged();
    partial void OnExamesChanging(string value);
    partial void OnExamesChanged();
    partial void OnIndicacaoCirurgiaChanging(System.Nullable<bool> value);
    partial void OnIndicacaoCirurgiaChanged();
    partial void OnDataPrevistaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPrevistaChanged();
    partial void OnResultadoEsperadoChanging(string value);
    partial void OnResultadoEsperadoChanged();
    partial void OnJustificativaChanging(string value);
    partial void OnJustificativaChanged();
    partial void OnPlanejamentoCirurgicoChanging(string value);
    partial void OnPlanejamentoCirurgicoChanged();
    partial void OnCreatedAtChanging(System.DateTime value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTime value);
    partial void OnUpdatedAtChanged();
    partial void OnDataCirurgiaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCirurgiaChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    #endregion
		
		public ConsultasMedica()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteId", DbType="Int NOT NULL")]
		public int PacienteId
		{
			get
			{
				return this._PacienteId;
			}
			set
			{
				if ((this._PacienteId != value))
				{
					this.OnPacienteIdChanging(value);
					this.SendPropertyChanging();
					this._PacienteId = value;
					this.SendPropertyChanged("PacienteId");
					this.OnPacienteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicoId", DbType="Int NOT NULL")]
		public int MedicoId
		{
			get
			{
				return this._MedicoId;
			}
			set
			{
				if ((this._MedicoId != value))
				{
					this.OnMedicoIdChanging(value);
					this.SendPropertyChanging();
					this._MedicoId = value;
					this.SendPropertyChanged("MedicoId");
					this.OnMedicoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospitalId", DbType="Int NOT NULL")]
		public int HospitalId
		{
			get
			{
				return this._HospitalId;
			}
			set
			{
				if ((this._HospitalId != value))
				{
					this.OnHospitalIdChanging(value);
					this.SendPropertyChanging();
					this._HospitalId = value;
					this.SendPropertyChanged("HospitalId");
					this.OnHospitalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CirurgiaId", DbType="Int NOT NULL")]
		public int CirurgiaId
		{
			get
			{
				return this._CirurgiaId;
			}
			set
			{
				if ((this._CirurgiaId != value))
				{
					this.OnCirurgiaIdChanging(value);
					this.SendPropertyChanging();
					this._CirurgiaId = value;
					this.SendPropertyChanged("CirurgiaId");
					this.OnCirurgiaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FornecedorId", DbType="Int NOT NULL")]
		public int FornecedorId
		{
			get
			{
				return this._FornecedorId;
			}
			set
			{
				if ((this._FornecedorId != value))
				{
					this.OnFornecedorIdChanging(value);
					this.SendPropertyChanging();
					this._FornecedorId = value;
					this.SendPropertyChanged("FornecedorId");
					this.OnFornecedorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Historico", DbType="VarChar(MAX)")]
		public string Historico
		{
			get
			{
				return this._Historico;
			}
			set
			{
				if ((this._Historico != value))
				{
					this.OnHistoricoChanging(value);
					this.SendPropertyChanging();
					this._Historico = value;
					this.SendPropertyChanged("Historico");
					this.OnHistoricoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataConsulta", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataConsulta
		{
			get
			{
				return this._DataConsulta;
			}
			set
			{
				if ((this._DataConsulta != value))
				{
					this.OnDataConsultaChanging(value);
					this.SendPropertyChanging();
					this._DataConsulta = value;
					this.SendPropertyChanged("DataConsulta");
					this.OnDataConsultaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Queixa", DbType="VarChar(MAX)")]
		public string Queixa
		{
			get
			{
				return this._Queixa;
			}
			set
			{
				if ((this._Queixa != value))
				{
					this.OnQueixaChanging(value);
					this.SendPropertyChanging();
					this._Queixa = value;
					this.SendPropertyChanged("Queixa");
					this.OnQueixaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HistoriaDoenca", DbType="VarChar(MAX)")]
		public string HistoriaDoenca
		{
			get
			{
				return this._HistoriaDoenca;
			}
			set
			{
				if ((this._HistoriaDoenca != value))
				{
					this.OnHistoriaDoencaChanging(value);
					this.SendPropertyChanging();
					this._HistoriaDoenca = value;
					this.SendPropertyChanged("HistoriaDoenca");
					this.OnHistoriaDoencaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExameFisico", DbType="VarChar(MAX)")]
		public string ExameFisico
		{
			get
			{
				return this._ExameFisico;
			}
			set
			{
				if ((this._ExameFisico != value))
				{
					this.OnExameFisicoChanging(value);
					this.SendPropertyChanging();
					this._ExameFisico = value;
					this.SendPropertyChanged("ExameFisico");
					this.OnExameFisicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diagnostico", DbType="VarChar(MAX)")]
		public string Diagnostico
		{
			get
			{
				return this._Diagnostico;
			}
			set
			{
				if ((this._Diagnostico != value))
				{
					this.OnDiagnosticoChanging(value);
					this.SendPropertyChanging();
					this._Diagnostico = value;
					this.SendPropertyChanged("Diagnostico");
					this.OnDiagnosticoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exames", DbType="VarChar(MAX)")]
		public string Exames
		{
			get
			{
				return this._Exames;
			}
			set
			{
				if ((this._Exames != value))
				{
					this.OnExamesChanging(value);
					this.SendPropertyChanging();
					this._Exames = value;
					this.SendPropertyChanged("Exames");
					this.OnExamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndicacaoCirurgia", DbType="Bit")]
		public System.Nullable<bool> IndicacaoCirurgia
		{
			get
			{
				return this._IndicacaoCirurgia;
			}
			set
			{
				if ((this._IndicacaoCirurgia != value))
				{
					this.OnIndicacaoCirurgiaChanging(value);
					this.SendPropertyChanging();
					this._IndicacaoCirurgia = value;
					this.SendPropertyChanged("IndicacaoCirurgia");
					this.OnIndicacaoCirurgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataPrevista", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataPrevista
		{
			get
			{
				return this._DataPrevista;
			}
			set
			{
				if ((this._DataPrevista != value))
				{
					this.OnDataPrevistaChanging(value);
					this.SendPropertyChanging();
					this._DataPrevista = value;
					this.SendPropertyChanged("DataPrevista");
					this.OnDataPrevistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultadoEsperado", DbType="VarChar(MAX)")]
		public string ResultadoEsperado
		{
			get
			{
				return this._ResultadoEsperado;
			}
			set
			{
				if ((this._ResultadoEsperado != value))
				{
					this.OnResultadoEsperadoChanging(value);
					this.SendPropertyChanging();
					this._ResultadoEsperado = value;
					this.SendPropertyChanged("ResultadoEsperado");
					this.OnResultadoEsperadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Justificativa", DbType="VarChar(MAX)")]
		public string Justificativa
		{
			get
			{
				return this._Justificativa;
			}
			set
			{
				if ((this._Justificativa != value))
				{
					this.OnJustificativaChanging(value);
					this.SendPropertyChanging();
					this._Justificativa = value;
					this.SendPropertyChanged("Justificativa");
					this.OnJustificativaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanejamentoCirurgico", DbType="VarChar(MAX)")]
		public string PlanejamentoCirurgico
		{
			get
			{
				return this._PlanejamentoCirurgico;
			}
			set
			{
				if ((this._PlanejamentoCirurgico != value))
				{
					this.OnPlanejamentoCirurgicoChanging(value);
					this.SendPropertyChanging();
					this._PlanejamentoCirurgico = value;
					this.SendPropertyChanged("PlanejamentoCirurgico");
					this.OnPlanejamentoCirurgicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCirurgia", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataCirurgia
		{
			get
			{
				return this._DataCirurgia;
			}
			set
			{
				if ((this._DataCirurgia != value))
				{
					this.OnDataCirurgiaChanging(value);
					this.SendPropertyChanging();
					this._DataCirurgia = value;
					this.SendPropertyChanged("DataCirurgia");
					this.OnDataCirurgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
